### ISSUE TITLE
window splitting not working

### ISSUE THREAD

**Issue by mirosval** [zdcthomas/dmux#22]
Hello and thank you for creating this! It looks like an awesome tool!

I have one issue:

My `~/.config/dmux/dmux.conf.toml` looks like this:

```toml
dir = "~/work"
session_name = "work"
number_of_panes = 2
commands = ["nvim", "zsh"]
```

but when I run `dmux <project>` or even `dmux -c nvim zsh -p 2 <project>` inside my tmux session, I can see the new window being created, but it is not split in two. There is only one panel with zsh.

Is this a bug or am I doing something wrong?
